// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdvcsywmqtlsrojolhlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkdmNzeXdtcXRsc3Jvam9saGxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNzU3NTcsImV4cCI6MjA3Mjg1MTc1N30.hmcrXIf_p725EHnHWpATGiPu9CXV9lkp3gaXy5FN5aE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});