project_id = "bdvcsywmqtlsrojolhlq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[functions.generate-image]
verify_jwt = false

[functions.process-video]
verify_jwt = false